steps:
  - name: 'gcr.io/cloud-builders/gcloud'

    args: [
      "run",
      "deploy",
      "cloudrunservice",
      "--image",
      "$_RUST_SINGLE_THREADED_DOCKER_REPO",
      "--region",
      "$_REGION",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--port",
      "$_PORT"
    ]
substitutions:
  _PORT: "8000"
  _REGION: us-central1
  _RUST_SINGLE_THREADED_DOCKER_REPO: us-central1-docker.pkg.dev/${PROJECT_ID}/rust-single-threaded-web-server/server-image:latest
  _SERVICE_NAME: 
options:
  dynamic_substitutions: true