steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: multithreadedserver
    args: ['build', '.', '-t', '$_RUST_MULTI_THREADED_DOCKER_REPO']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_RUST_MULTI_THREADED_DOCKER_REPO']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      "run",
      "deploy",
      "$_SERVICE_NAME",
      "--image",
      "$_RUST_MULTI_THREADED_DOCKER_REPO",
      "--region",
      "$_REGION",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      "--port",
      "$_PORT"
    ]
substitutions:
  _PORT: "8000"
  _REGION: us-central1
  _SERVICE_NAME: multithreadrustserver
  _RUST_MULTI_THREADED_DOCKER_REPO: us-central1-docker.pkg.dev/${PROJECT_ID}/rust-multi-threaded-web-server/server-image:latest
options:
  dynamic_substitutions: true

